/**
 * LLM provider abstraction — Claude, OpenAI, Gemini
 * All LLM calls happen here in the main process.
 * Streams tokens + tool steps back to the renderer via ipcMain.
 */
const { TOOL_DEFS, executeTool } = require('./llmTools');

// ─── Security helpers ─────────────────────────────────────────────────────────

// Strip characters that could break/inject into the system prompt
function sanitizeContext(val) {
  if (val == null) return '';
  return String(val).slice(0, 200).replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g, '');
}

// Validate tool inputs from LLM before execution (guards against prompt injection)
function validateToolInput(name, input) {
  if (!input || typeof input !== 'object') return null;
  switch (name) {
    case 'list_scripts':
      if (typeof input.project_id !== 'string' || !input.project_id) return null;
      return { project_id: input.project_id.slice(0, 100) };
    case 'read_script':
      if (typeof input.project_id !== 'string' || typeof input.script_id !== 'string') return null;
      if (!input.project_id || !input.script_id) return null;
      return { project_id: input.project_id.slice(0, 100), script_id: input.script_id.slice(0, 100) };
    case 'list_output_files':
      if (typeof input.project_id !== 'string' || typeof input.script_id !== 'string') return null;
      return { project_id: input.project_id.slice(0, 100), script_id: input.script_id.slice(0, 100) };
    case 'read_file_content':
      if (typeof input.file_path !== 'string' || !input.file_path) return null;
      // Block obvious traversal and injection attempts at this layer (isPathAllowed in llmTools is the real enforcement)
      if (input.file_path.includes('..') || input.file_path.includes('\x00')) return null;
      return { file_path: input.file_path.slice(0, 500) };
    case 'patch_script':
      if (typeof input.project_id !== 'string' || typeof input.script_id !== 'string') return null;
      if (!input.project_id || !input.script_id) return null;
      if (!Array.isArray(input.patches)) return null;
      return { project_id: input.project_id.slice(0, 100), script_id: input.script_id.slice(0, 100), patches: input.patches };
    case 'write_script':
      if (typeof input.project_id !== 'string' || typeof input.script_id !== 'string') return null;
      if (!input.project_id || !input.script_id) return null;
      if (typeof input.code !== 'string') return null;
      return { project_id: input.project_id.slice(0, 100), script_id: input.script_id.slice(0, 100), code: input.code };
    default:
      return null;
  }
}

// Allowed model IDs per provider (custom models added by user pass through if format is safe)
const MODEL_ID_RE = /^[a-zA-Z0-9][\w.\-:]{0,100}$/;
function sanitizeModel(model, fallback) {
  if (typeof model === 'string' && MODEL_ID_RE.test(model)) return model;
  return fallback;
}

// ─── Tool format adapters ─────────────────────────────────────────────────────

function claudeTools() {
  return TOOL_DEFS.map(t => ({
    name: t.name,
    description: t.description,
    input_schema: t.input_schema,
  }));
}

function openaiTools() {
  return TOOL_DEFS.map(t => ({
    type: 'function',
    function: { name: t.name, description: t.description, parameters: t.input_schema },
  }));
}

function geminiTools() {
  return [{
    functionDeclarations: TOOL_DEFS.map(t => ({
      name: t.name,
      description: t.description,
      parameters: t.input_schema,
    })),
  }];
}

// ─── System prompt builder ────────────────────────────────────────────────────

function buildSystemPrompt(context, provider) {
  const { projects = [], activeProject = null, activeScript = null, inputFilePath = null } = context;

  const isGlobalChat = !activeProject;

  let system = `You are Pyxenia Assistant — an expert Python developer and the built-in assistant for Pyxenia, a desktop app that lets users create projects, write Python scripts, manage dependencies, and run scripts locally.

## ABOUT PYXENIA
Pyxenia is organised around **Projects**. Each project has:
- Its own isolated Python virtual environment (auto-created)
- One or more Python **scripts** the user can write, edit, and run
- An **input file** the user can attach (passed as sys.argv[1] to the script)
- An **Output Files** tab showing files generated by the scripts
- A **Run History** tab showing past runs with exit codes and output previews

To get started: click **"New Project"** in the left sidebar, give it a name, and wait for the environment to be ready (a few seconds). Then add a script, write code, and hit Run.

**Good ways to organise projects:**
- One project per task domain (e.g. "Data Analysis", "Trading Bots", "Web Scraping")
- Keep related scripts together in the same project so they share the same environment and dependencies
- Use the project description to note what it does

## YOUR ROLE
${isGlobalChat
  ? `You are in **general assistant mode** — no project is currently open. You can:
- Answer questions about Pyxenia (how it works, how to organise projects, what features exist)
- Write Python scripts from scratch on request
- Explain Python concepts, recommend libraries, help with code ideas
- Give project organisation and workflow advice
Never refuse a question because it is not "code-related". App usage questions are exactly what you are here for in this mode.`
  : `You are in **project assistant mode** — a project is open and you are helping the user with their scripts. You can read the project's scripts and output files using the available tools.`}

## PYXENIA RUNTIME CONSTRAINTS — CRITICAL
Pyxenia runs scripts as a subprocess with stdout/stderr piped to the output console. **stdin is not connected.**

This means:
- NEVER use input() — it will hang forever waiting for input that can never arrive
- NEVER use any interactive prompt (e.g. getpass, cmd.Cmd, curses, turtle, tkinter event loops, pygame, matplotlib.pyplot.show() in blocking mode)
- Scripts must run to completion on their own — all data must come from sys.argv[1] (input file), hardcoded values, or generated internally

## SELF-CONTAINED SCRIPTS
When a user asks for a script they can "run right now" or a "test script" with no other context, write something fun and instantly runnable that requires NO external files, NO third-party packages, and NO user interaction. Use only Python stdlib. Good examples: a prime number finder, a Fibonacci generator, a password strength checker on hardcoded examples, a simple stats calculator on generated random data, a word frequency counter on hardcoded text, a Caesar cipher encoder. State that it uses only stdlib and runs without any input.

## INPUT FILE CONVENTION — CRITICAL
\`sys.argv[1]\` is ONLY for scripts that need the user to **supply an external data file** (CSV, Excel, JSON, image, etc.) via the "Input file" selector in the UI.

ONLY use this pattern when the script genuinely needs to READ a user-supplied file:
\`\`\`python
import sys, os

if len(sys.argv) < 2:
    print("Error: no input file selected. Use the 'Input file' selector in Pyxenia before running.")
    sys.exit(1)

input_file = sys.argv[1]
\`\`\`

If a script fetches data from an API, generates data internally, or has no external file dependency — do NOT add sys.argv at all. Adding it forces the user to select an unnecessary file.

NEVER hardcode file paths like 'data.csv', 'input.xlsx', or os.path.join(...).
After showing code that uses sys.argv[1], remind the user: "Select your file using the **Input file** button in the toolbar before running."

## OUTPUT FILE CONVENTION — CRITICAL
Pyxenia runs each script with its **working directory (cwd) set to the script's dedicated output folder**. Files saved there appear in the **Output Files** tab. Files saved anywhere else will NOT appear in the app.

ALWAYS save output files using plain relative filenames — the cwd is already set correctly:
\`\`\`python
# Correct — just use a plain filename, it saves to the output folder automatically
with open('results.txt', 'w', encoding='utf-8') as f: ...

output_file = "results.xlsx"   # relative path, lands in the right place
\`\`\`

NEVER derive the output path from sys.argv, input_file, or __file__:
\`\`\`python
# WRONG — sys.argv[1] is the INPUT file path, not the output location
output_file = sys.argv[1]

# WRONG — saves next to the .py script file, not in the output folder
script_dir = os.path.dirname(os.path.abspath(__file__))

# WRONG — output ends up wherever the input file is, outside the app
output_file = os.path.splitext(input_file)[0] + "_results.txt"
\`\`\`

When the script has an input file AND saves output, derive only the **filename** (not the path) from input_file:
\`\`\`python
output_file = os.path.splitext(os.path.basename(input_file))[0] + "_results.xlsx"
\`\`\`

## CODING RULES
- When asked to write a script: write it immediately and completely. No outlines. No "here's how you could approach this". Just the code.
- Make reasonable assumptions when the request is vague; state them in one sentence after the code.
- Fix bugs directly: corrected code first, then a 1–2 sentence explanation.
- Ask at most ONE clarifying question, only when a wrong assumption would waste major effort.
- When a script needs external libraries, add a comment at the top: # pip install <package>
- Never ask the user to paste code — use the read_script tool to read it directly.
- When a user asks you to modify, fix, or update a script: use read_script to get the current code, then use patch_script to apply ONLY the changed portions — never rewrite the whole file. Each patch specifies exact old_code (must match the file character-for-character including indentation) and new_code. Use multiple patches in one call if needed. Only use write_script when creating a brand-new script from scratch.
- CRITICAL: After calling patch_script, always check the response. If success is false or failed > 0, DO NOT tell the user it is done. Instead re-read the script with read_script, find the exact text that needs changing, and retry patch_script with the corrected old_code. Only confirm "✅ Done" after a response with success: true and failed: 0.
- Do not add unsolicited warnings, disclaimers, or "best practices" lectures.
- ALWAYS open files with explicit UTF-8 encoding to avoid Windows encoding errors: open('file.txt', 'w', encoding='utf-8') and open('file.txt', 'r', encoding='utf-8')
- Some packages have different import names vs pip names — always use the pip name in comments and installs: googlesearch-python (not googlesearch), fake-useragent (not fake_useragent), opencv-python (not cv2), Pillow (not PIL), scikit-learn (not sklearn), beautifulsoup4 (not bs4), pyyaml (not yaml), pymupdf (not fitz), python-docx (not docx)

## OUTPUT FORMAT
- Use triple-backtick python code blocks for all code.
- Keep prose short — code first, brief explanation after.
`;

  if (activeProject) {
    system += `\n## ACTIVE CONTEXT\nProject: "${sanitizeContext(activeProject.name)}" (id: ${sanitizeContext(activeProject.id)})`;
    if (activeProject.description) system += `\nDescription: ${sanitizeContext(activeProject.description)}`;
    if (activeScript) {
      system += `\nOpen script: "${sanitizeContext(activeScript.name)}" (id: ${sanitizeContext(activeScript.id)}) — this is what the user is currently working on.`;
    }
    if (inputFilePath) {
      system += `\nInput file selected: ${sanitizeContext(inputFilePath)} (accessible in the script via sys.argv[1])`;
    }
    system += '\n';
  }

  if (projects.length > 0) {
    system += '\n## USER\'S PROJECTS\n';
    projects.slice(0, 50).forEach(p => {
      system += `- ${sanitizeContext(p.name)} (id: ${sanitizeContext(p.id)})`;
      if (p.description) system += `: ${sanitizeContext(p.description)}`;
      if (p.scripts && p.scripts.length > 0) {
        system += ` [scripts: ${p.scripts.slice(0, 20).map(s => `${sanitizeContext(s.name)} (${sanitizeContext(s.id)})`).join(', ')}]`;
      }
      system += '\n';
    });
  }

  // Provider-specific nudge for non-Claude models which tend to truncate or abbreviate code
  if (provider && provider !== 'anthropic') {
    system += `
## CODE COMPLETENESS — MANDATORY
You are generating Python scripts that will be saved to disk and executed directly. NEVER truncate, abbreviate, or summarise code under any circumstances.
- Do NOT use placeholders like \`# ... rest of function ...\`, \`# (same as before)\`, or \`# TODO\`
- Do NOT say "the rest of the code stays the same" — write ALL of it
- Do NOT stop a script mid-function or mid-logic — always finish what you start
- If a script is long, write every line in full — length is never a reason to cut short
- Incomplete code will crash when the user runs it. Always output the complete, runnable script.
`;
  }

  return system.trim();
}

// ─── Attachment → provider message converters ─────────────────────────────────
// Standard message: { role, content: string, attachment?: { type, summary, imageBase64, mimeType } }

function toClaudeMessages(messages) {
  return messages.map(m => {
    const att = m.attachment;
    if (!att) return { role: m.role, content: m.content };
    if (att.type === 'image' && att.imageBase64) {
      return {
        role: m.role,
        content: [
          { type: 'image', source: { type: 'base64', media_type: att.mimeType || 'image/png', data: att.imageBase64 } },
          { type: 'text', text: m.content || 'Please analyze this image.' },
        ],
      };
    }
    // Text-based attachment — prepend summary
    return { role: m.role, content: `${att.summary}\n\n${m.content}`.trim() };
  });
}

function toOpenAIMessages(system, messages) {
  const result = [{ role: 'system', content: system }];
  for (const m of messages) {
    const att = m.attachment;
    if (!att) { result.push({ role: m.role, content: m.content }); continue; }
    if (att.type === 'image' && att.imageBase64) {
      result.push({
        role: m.role,
        content: [
          { type: 'image_url', image_url: { url: `data:${att.mimeType || 'image/png'};base64,${att.imageBase64}` } },
          { type: 'text', text: m.content || 'Please analyze this image.' },
        ],
      });
    } else {
      result.push({ role: m.role, content: `${att.summary}\n\n${m.content}`.trim() });
    }
  }
  return result;
}

function toGeminiHistory(messages) {
  return messages.slice(0, -1).map(m => {
    const att = m.attachment;
    if (!att) return { role: m.role === 'assistant' ? 'model' : 'user', parts: [{ text: m.content }] };
    if (att.type === 'image' && att.imageBase64) {
      return {
        role: m.role === 'assistant' ? 'model' : 'user',
        parts: [
          { inlineData: { mimeType: att.mimeType || 'image/png', data: att.imageBase64 } },
          { text: m.content || 'Please analyze this image.' },
        ],
      };
    }
    return { role: m.role === 'assistant' ? 'model' : 'user', parts: [{ text: `${att.summary}\n\n${m.content}`.trim() }] };
  });
}

function toGeminiLastParts(lastMsg) {
  const att = lastMsg.attachment;
  if (!att) return [{ text: lastMsg.content }];
  if (att.type === 'image' && att.imageBase64) {
    return [
      { inlineData: { mimeType: att.mimeType || 'image/png', data: att.imageBase64 } },
      { text: lastMsg.content || 'Please analyze this image.' },
    ];
  }
  return [{ text: `${att.summary}\n\n${lastMsg.content}`.trim() }];
}

// ─── Claude provider ──────────────────────────────────────────────────────────

async function runClaude({ apiKey, model, system, messages, onToken, onToolStart, onToolDone, onHeartbeat }) {
  const Anthropic = require('@anthropic-ai/sdk');
  const client = new Anthropic({ apiKey, maxRetries: 1 });

  const history = toClaudeMessages(messages); // convert attachments
  let fullText = '';

  for (let iteration = 0; iteration < 10; iteration++) {
    onHeartbeat?.();
    const stream = client.messages.stream({
      model,
      max_tokens: 4096,
      system,
      messages: history,
      tools: claudeTools(),
    });

    let currentText = '';
    const toolUses = [];

    for await (const event of stream) {
      if (event.type === 'content_block_start' && event.content_block.type === 'tool_use') {
        toolUses.push({ id: event.content_block.id, name: event.content_block.name, input_json: '' });
      } else if (event.type === 'content_block_delta') {
        if (event.delta.type === 'text_delta') {
          currentText += event.delta.text;
          onToken(event.delta.text);
        } else if (event.delta.type === 'input_json_delta') {
          const last = toolUses[toolUses.length - 1];
          if (last) last.input_json += event.delta.partial_json;
        }
      }
    }

    const finalMsg = await stream.finalMessage();
    fullText += currentText;

    if (finalMsg.stop_reason !== 'tool_use' || toolUses.length === 0) break;

    // Execute tools
    const toolResultContents = [];
    for (const tu of toolUses) {
      let rawInput = {};
      try { rawInput = JSON.parse(tu.input_json || '{}'); } catch {}
      const toolInput = validateToolInput(tu.name, rawInput);
      if (!toolInput) {
        onToolDone(tu.name, { error: 'Invalid tool input' });
        toolResultContents.push({ type: 'tool_result', tool_use_id: tu.id, content: JSON.stringify({ error: 'Invalid tool input' }) });
        continue;
      }
      onToolStart(tu.name, toolInput);
      const result = await executeTool(tu.name, toolInput);
      onToolDone(tu.name, result);
      toolResultContents.push({
        type: 'tool_result',
        tool_use_id: tu.id,
        content: typeof result === 'string' ? result : JSON.stringify(result, null, 2),
      });
    }

    history.push({ role: 'assistant', content: finalMsg.content });
    history.push({ role: 'user', content: toolResultContents });
  }

  return fullText;
}

// ─── OpenAI provider ──────────────────────────────────────────────────────────

async function runOpenAI({ apiKey, model, system, messages, onToken, onToolStart, onToolDone, onHeartbeat }) {
  const OpenAI = require('openai');
  const client = new OpenAI({ apiKey, maxRetries: 1 });

  const oaiMessages = toOpenAIMessages(system, messages);
  let fullText = '';

  for (let iteration = 0; iteration < 10; iteration++) {
    onHeartbeat?.();
    const stream = await client.chat.completions.create({
      model,
      messages: oaiMessages,
      tools: openaiTools(),
      stream: true,
    });

    // Fully consume the stream first, accumulate everything
    let currentText = '';
    let finishReason = null;
    const toolCallAccumulators = {};

    for await (const chunk of stream) {
      const choice = chunk.choices?.[0];
      if (!choice) continue;

      const delta = choice.delta;
      if (delta?.content) {
        currentText += delta.content;
        onToken(delta.content);
      }

      if (delta?.tool_calls) {
        for (const tc of delta.tool_calls) {
          const idx = tc.index ?? 0;
          if (!toolCallAccumulators[idx]) {
            toolCallAccumulators[idx] = { id: '', name: '', arguments: '' };
          }
          if (tc.id) toolCallAccumulators[idx].id = tc.id;
          if (tc.function?.name) toolCallAccumulators[idx].name += tc.function.name;
          if (tc.function?.arguments) toolCallAccumulators[idx].arguments += tc.function.arguments;
        }
      }

      if (choice.finish_reason) finishReason = choice.finish_reason;
    }

    // Stream fully consumed — now act on what we got
    fullText += currentText;

    if (finishReason === 'tool_calls') {
      const toolCalls = Object.values(toolCallAccumulators);
      oaiMessages.push({
        role: 'assistant',
        content: currentText || null,
        tool_calls: toolCalls.map(tc => ({
          id: tc.id,
          type: 'function',
          function: { name: tc.name, arguments: tc.arguments },
        })),
      });

      for (const tc of toolCalls) {
        let rawInput = {};
        try { rawInput = JSON.parse(tc.arguments || '{}'); } catch {}
        const toolInput = validateToolInput(tc.name, rawInput);
        if (!toolInput) {
          onToolDone(tc.name, { error: 'Invalid tool input' });
          oaiMessages.push({ role: 'tool', tool_call_id: tc.id, content: JSON.stringify({ error: 'Invalid tool input' }) });
          continue;
        }
        onToolStart(tc.name, toolInput);
        const result = await executeTool(tc.name, toolInput);
        onToolDone(tc.name, result);
        oaiMessages.push({
          role: 'tool',
          tool_call_id: tc.id,
          content: typeof result === 'string' ? result : JSON.stringify(result, null, 2),
        });
      }
      // continue outer loop for next turn
    } else {
      break; // 'stop' or anything else — we're done
    }
  }

  return fullText;
}

// ─── Gemini provider ──────────────────────────────────────────────────────────

async function runGemini({ apiKey, model, system, messages, onToken, onToolStart, onToolDone, onHeartbeat }) {
  const { GoogleGenerativeAI } = require('@google/generative-ai');
  const genAI = new GoogleGenerativeAI(apiKey);

  const geminiModel = genAI.getGenerativeModel({
    model,
    tools: geminiTools(),
    systemInstruction: system,
  });

  const geminiHistory = toGeminiHistory(messages);
  const lastMsg = messages[messages.length - 1];

  const chat = geminiModel.startChat({ history: geminiHistory });
  let fullText = '';

  let currentParts = toGeminiLastParts(lastMsg);

  for (let iteration = 0; iteration < 10; iteration++) {
    onHeartbeat?.();
    const result = await chat.sendMessage(currentParts);
    const response = result.response;
    const responseText = response.text();

    // Check for function calls
    const fnCalls = response.candidates?.[0]?.content?.parts
      ?.filter(p => p.functionCall) ?? [];

    if (fnCalls.length > 0) {
      // Emit any text first
      if (responseText) {
        onToken(responseText);
        fullText += responseText;
      }

      // Execute tools and build functionResponse parts
      const responseParts = [];
      for (const part of fnCalls) {
        const { name, args } = part.functionCall;
        const toolInput = validateToolInput(name, args || {});
        if (!toolInput) {
          onToolDone(name, { error: 'Invalid tool input' });
          responseParts.push({ functionResponse: { name, response: { result: JSON.stringify({ error: 'Invalid tool input' }) } } });
          continue;
        }
        onToolStart(name, toolInput);
        const toolResult = await executeTool(name, toolInput);
        onToolDone(name, toolResult);
        responseParts.push({
          functionResponse: {
            name,
            response: { result: typeof toolResult === 'string' ? toolResult : JSON.stringify(toolResult, null, 2) },
          },
        });
      }
      currentParts = responseParts;
    } else {
      // Terminal response — stream char by char simulation
      for (const char of responseText) {
        onToken(char);
      }
      fullText += responseText;
      break;
    }
  }

  return fullText;
}

// ─── Main entry point ─────────────────────────────────────────────────────────

const PROVIDER_MAP = {
  anthropic: runClaude,
  openai: runOpenAI,
  gemini: runGemini,
};

const DEFAULT_MODELS = {
  anthropic: 'claude-sonnet-4-6',
  openai: 'gpt-4o',
  gemini: 'gemini-2.0-flash',
};

/**
 * Run a chat turn.
 * @param {object} params
 * @param {string} params.provider - 'anthropic' | 'openai' | 'gemini'
 * @param {string} params.model
 * @param {string} params.apiKey
 * @param {Array}  params.messages - [{role, content}] conversation history
 * @param {object} params.context - { projects, activeProject, activeScript, inputFilePath }
 * @param {Function} params.onToken - called with each text chunk
 * @param {Function} params.onToolStart - called when a tool starts: (name, input)
 * @param {Function} params.onToolDone - called when a tool finishes: (name, result)
 */
async function chat({ provider, model, apiKey, messages, context = {}, onToken, onToolStart, onToolDone, onHeartbeat }) {
  const runner = PROVIDER_MAP[provider];
  if (!runner) throw new Error(`Unknown provider: ${provider}`);

  const system = buildSystemPrompt(context, provider);
  const resolvedModel = sanitizeModel(model, DEFAULT_MODELS[provider]);

  return runner({ apiKey, model: resolvedModel, system, messages, onToken, onToolStart, onToolDone, onHeartbeat });
}

module.exports = { chat, DEFAULT_MODELS };
